# Generated by Django 5.1.7 on 2025-03-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksession',
            options={'ordering': ['-started_at', '-ended_at']},
        ),
        migrations.AlterField(
            model_name='worksession',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
