# Generated by Django 5.1.7 on 2025-03-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0002_alter_worksession_options_alter_worksession_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration, mins'),
        ),
    ]
