# Generated by Django 5.1.7 on 2025-05-16 13:26

import django.db.models.deletion
import wtt.work_sessions.models
from django.conf import settings
from django.db import migrations, models

def create_stub_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    username = 'stub'
    try:
        User.objects.get(username=username)
    except:
        User.objects.create_user(username=username)


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0003_alter_worksession_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_stub_user),
        migrations.AddField(
            model_name='worksession',
            name='owner',
            field=models.ForeignKey(default=wtt.work_sessions.models.WorkSession.owner_default, on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
