# Generated by Django 5.1.7 on 2025-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0004_worksession_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='note',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
