# Generated by Django 5.1.7 on 2025-05-17 10:15

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0005_alter_worksession_note'),
    ]

    operations = [
        TrigramExtension(),
    ]
