# Generated by Django 5.1.7 on 2025-05-17 10:35

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0006_auto_20250517_1015'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='worksession',
            index=django.contrib.postgres.indexes.GinIndex(fields=['note'], name='note_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
