# Generated by Django 5.1.7 on 2025-05-17 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0007_worksession_note_trgm_gin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSessionLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_session_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wtt_work_session_label',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='worksession',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='work_sessions', to='work_sessions.worksessionlabel'),
        ),
        migrations.AddConstraint(
            model_name='worksessionlabel',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_name_owner'),
        ),
    ]
