# Generated by Django 5.1.7 on 2025-05-23 11:39

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0008_worksessionlabel_worksession_labels_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='worksessionlabel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='wsl_name_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
