# Generated by Django 5.1.7 on 2025-07-12 08:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0009_worksessionlabel_wsl_name_trgm_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
